### PR TITLE
Removed the jquery usage

### PR DESCRIPTION
**Pull request by raghavbk**
Removed the jquery usages from service and component, replace that with native dom query

### CODE REVIEW

**Comment by rwwagner90** [comment]
@cbroeren any chance we could get this merged?

**Comment by cbroeren** [comment]
@rwwagner90 I will try to see how we can run the tests, so we can be sure everything is still fine

**Comment by rwwagner90** [comment]
@cbroeren I am using this in my app and it works. It appears there is a Travis build that used to run. Was it removed from the repo?

**Comment by rwwagner90** [comment]
@cbroeren if you want to add me as a maintainer, I can help setup Travis and get the tests running. It would be good to get things updated here, so I do not have to use my fork.

**Pull request closed without merging**
